apiVersion: 1

datasources:
  - name: InfluxDB-RPiCar
    type: influxdb
    access: proxy
    url: http://rpicar_influxdb:8086
    # If Grafana container can't reach influxdb by container name,
    # the server_setup.sh will patch this to http://localhost:8086
    jsonData:
      version: Flux
      organization: rpicar
      defaultBucket: car_telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: rpicar-secret-token-change-me
    isDefault: true
    editable: true
