apiVersion: 1
datasources:
  - name: InfluxDB-RPiCar
    uid: influxdb-rpicar
    type: influxdb
    access: proxy
    url: http://172.17.0.1:8086
    database: car_telemetry
    isDefault: true
    editable: true
    jsonData:
      version: "InfluxQL"
      httpMode: "GET"
      timeInterval: "500ms"
